sudo: required

services:
  - docker

before_install:
  - docker build -t amruthpillai/react-docker -f Dockerfile.dev .

script:
  - docker run amruthpillai/react-docker npm run test -- --coverage

deploy:
  provider: elasticbeanstalk
  region: "us-east-2"
  app: "ReactApp"
  env: "Reactapp-env"
  bucket_name: "elasticbeanstalk-us-east-2-731883578346"
  bucket_path: "ReactApp"
  on:
    branch: master
  access_key_id: "$AWS_ACCESS_KEY"
  secret_access_key:
    secure: "$AWS_SECRET_KEY"